/** Room feeds - multi-market from market_feed.json **/
#include "types.h"
#include "paper_feature_bridge.h"
#include <sqlite3.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <jansson.h>

#define MARKET_FEED_PATH "/home/wubu2/.hermes/pm_logs/c_room/market_feed.json"

static int64_t g_last_ts = 0;
static int g_first_call = 1;

static double json_get_num(const char *json, const char *key) {
    char search[128];
    snprintf(search, sizeof(search), "\"%s\":", key);
    const char *p = strstr(json, search);
    if (!p) return 0;
    p += strlen(search);
    while (*p == ' ' || *p == '\t') p++;
    return atof(p);
}

static const char *json_get_str(const char *json, const char *key, char *out, size_t sz) {
    char search[128];
    snprintf(search, sizeof(search), "\"%s\":\"", key);
    const char *p = strstr(json, search);
    if (!p) return "";
    p += strlen(search);
    const char *end = strchr(p, '"');
    if (!end) return "";
    size_t len = end - p;
    if (len >= sz) len = sz - 1;
    memcpy(out, p, len);
    out[len] = '\0';
    return out;
}

RoomError room_feeds_load(MarketTick *tick) {
    // Read market_feed.json generated by feed_bridge
    FILE *f = fopen(MARKET_FEED_PATH, "r");
    if (!f) return ERR_FILE_READ;
    
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (len <= 0 || len > 1024*1024) { fclose(f); return ERR_FILE_READ; }
    
    char *json = malloc(len + 1);
    if (!json) { fclose(f); return ERR_FILE_READ; }
    fread(json, 1, len, f);
    json[len] = '\0';
    fclose(f);
    
    // Parse key fields
    memset(tick, 0, sizeof(MarketTick));
    tick->window_ts = (int64_t)json_get_num(json, "window_ts");
    json_get_str(json, "asset", tick->asset, sizeof(tick->asset));
    tick->open = (float)json_get_num(json, "open");
    tick->high = (float)json_get_num(json, "high");
    tick->low = (float)json_get_num(json, "low");
    tick->close = (float)json_get_num(json, "close");
    tick->volume = (float)json_get_num(json, "volume");
    tick->fear_greed = (float)json_get_num(json, "fear_greed");
    tick->pump_score = (float)json_get_num(json, "pump_score");
    tick->btc_dominance = (float)json_get_num(json, "btc_dominance");
    tick->vix = (float)json_get_num(json, "vix");
    tick->sp500 = (float)json_get_num(json, "sp500");
    tick->btc_30d_volatility = (float)json_get_num(json, "btc_30d_volatility");
    tick->btc_30d_mean = (float)json_get_num(json, "btc_30d_mean");
    tick->btc_30d_high = (float)json_get_num(json, "btc_30d_high");
    tick->btc_30d_low = (float)json_get_num(json, "btc_30d_low");
    
    // Check for duplicate timestamp (static feed) - handled by room_engine main loop
    g_last_ts = tick->window_ts;
    
    // Market type from feed
    double mt = json_get_num(json, "market_type");
    if (mt >= 0) tick->market_type = (MarketType)((int)mt);
    else tick->market_type = MARKET_CRYPTO;
    
    free(json);
    return ERR_OK;
}
